language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

notifications:
  irc: "irc.freenode.org##atoum"

before_script:
  - composer install

script:
  - vendor/bin/atoum --test-ext
